"""Compatibilidad: las utilidades de tuning viven ahora en utilidades.modelos."""

from utilidades.modelos import (  # noqa: F401
    CB_KEYS,
    FIT_KEYS,
    TrainEvalLoss,
    _build_model_from_modelos,
    _get_model_fn,
    _make_callbacks,
    _score_history,
    _train_one,
    construir_conv1d_param,
    construir_dense_param,
    construir_dense_v3_param,
    construir_dense_v5_param,
    construir_dense_v6_param,
    construir_dense_v2_param,
    construir_dense_v4_param,
    construir_lstm_param,
    construir_mixto_param,
    grid_search,
    ofat_search,
    plot_best_history,
    successive_halving_search,
)
